/**
 * DB script for the Nexmo plugin
 */
CREATE TABLE IF NOT EXISTS `nexmo` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nexmo_api_secret` VARCHAR(50) NOT NULL,
	`nexmo_api_key` VARCHAR(50) NOT NULL,
	`nexmo_phone_no` VARCHAR(25),
	`delivery_receipt_key` VARCHAR(255), -- Key for the delivery response callback URL
	`inbound_message_key` VARCHAR(255),  -- Key for the incoming message callback URL
	PRIMARY KEY (`id`)
);

/** Log of all messages sent via the nexmo plugin */
CREATE TABLE IF NOT EXISTS `nexmo_message_log` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`message_id` VARCHAR(255) NOT NULL UNIQUE KEY, -- Generated by the Nexmo gateway
	`message_recipient` VARCHAR(25),
	`message_sender` VARCHAR(25),
	`message_type` TINYINT NOT NULL DEFAULT 0, -- 0 -Outgoing 1 - Incoming
	`delivery_status` TINYINT, -- 0 Delivery status not received/not delivered 1 - Delivery succeeded
	PRIMARY KEY (`id`)
);